### ISSUE TITLE
Hello JackRao!

### ISSUE THREAD

**Issue by progressforever** [Archaic-Atom/JackFramework#56]
This framework is the best framework in the world.
Everyne should fork it.
Haha, I leave this message when i touch fish at work!

**Comment by RaoHaocheng** [comment]
But you have not forked it. I am angry.

**Comment by progressforever** [comment]
> But you have not forked it. I am angry.

The email about you close this issue jumps like fish from the sea.  I touch fish again at work! Fork it!
